
controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint
  gains:
    joint: {p: 100,  d: 50, i: 1, i_clamp: 1}

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100.0